# Retry and EIRP Limits
MAX_RETRY_RATE: 8.0
MAX_EIRP_RATE: 30.0
ANTENNA_GAIN_DB: 4.0
RETRY_RATE_PENALTY_DB: 20.0
EIRP_RATE_PENALTY_DB: 15.0

# Transmit Power Settings
TX_POWER_MIN_DBM: 17.0
TX_POWER_MAX_DBM: 30.0

# Channel and Noise Settings
CHANNEL_WIDTHS_MHZ: [20, 40]
NOISE_FLOOR_DBM: -95.0
MAX_OBSS_PD_DBM: -62.0
ANTENNA_GAIN_DBM: 4.0

# Observation and Cool-off Settings
MIN_ONLINE_OBSERVE_TIME_MINS: 2.0
ONLINE_OBSERVE_TIME : 8.0
CLIENT_COOL_OFF_THRESHOLD: 0.4
COMPLAINT_COOL_OFF_MIN: 30

# Offline Optimization Settings
INITIAL_OFFLINE_TRIALS: 50
OFFLINE_SLEEP_DELAY_SEC: 1

WINDOW_DURATION_HOURS: 3
SIM_ACCEL_FACTOR: 12